spring:
  application:
    name: practic-security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_practice
    username: postgres
    password: PosTer231
  app:
    jwtSecret: ${SIGNATURE}
    jwtExpirationMs: ${EXPIRATION}

  flyway:
    clean-on-validation-error: true
    cleanDisabled: false

logging:
  level:
    org:
      springframework:
        security: Debug
        hibernate:
          sql: DEBUG
      security:
        practic: Debug

